### ISSUE TITLE
An/Aus Status geht nicht (powerOn immer false)

### ISSUE THREAD

**Issue by redo82** [iobroker-community-adapters/ioBroker.samsung_tizen#26]
Der Wert von powerOn ist immer false obwohl der Fernseher an ist.
Einen Test ob der Adapter funktioniert konnte ich mit der Lautstäke erfolgreich testen. 

Logeintrag. Version 1.0.0 (non-npm: iobroker-community-adapters/ioBroker.samsung_tizen#60614d17654eaaf286401711b31b3c92769206dc) in /opt/iobroker/node_modules/iobroker.samsung_tizen, node: v18.18.0, js-controller: 5.0.12

**Comment by SentiQ** [comment]
Bei meinem älteren QE55Q7 wechselt der Status spätestens nach 10 Sekunden auf den korrekten Wert und auch wieder zurück, wenn sich dieser ändert.

**Comment by redo82** [comment]
Vielen Dank . Ich habe nochmal genauer geschaut und hatte den falschen Polling Port gewählt. Jetzt klappt es.
